# permissions for end users to edit purgestatuses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubepurge
    app.kubernetes.io/managed-by: kustomize
  name: purgestatus-editor-role
rules:
- apiGroups:
  - kubepurge.xyz
  resources:
  - purgestatuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubepurge.xyz
  resources:
  - purgestatuses/status
  verbs:
  - get
