---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - secrets
  - services
  verbs:
  - delete
  - get
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - delete
  - get
  - list
- apiGroups:
  - kubepurge.xyz
  resources:
  - purgepolicies
  - purgestatuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubepurge.xyz
  resources:
  - purgepolicies/finalizers
  verbs:
  - update
- apiGroups:
  - kubepurge.xyz
  resources:
  - purgepolicies/status
  verbs:
  - get
  - patch
  - update
