---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kubepurge.xyz
  resources:
  - purgepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubepurge.xyz
  resources:
  - purgepolicies/finalizers
  verbs:
  - update
- apiGroups:
  - kubepurge.xyz
  resources:
  - purgepolicies/status
  verbs:
  - get
  - patch
  - update
