apiVersion: kubepurge.xyz/v1
kind: PurgePolicy
metadata:
  labels:
    app.kubernetes.io/name: kubepurge
    app.kubernetes.io/managed-by: kustomize
  name: purgepolicy-sample
spec:
  targetNamespace: app1
  schedule: 16 20 * * *
  resources: 
  - "Pods"
  - "Deployments"
  

